### ISSUE TITLE
[Feat] Automated deployment to github pages

### ISSUE THREAD

**Issue by chrismclarke** [e-picsa/docs#2]
**Is your feature request related to a problem? Please describe.**
We would like a live website deployment of the documentation page, that is always kept updated

**Describe the solution you'd like**
Automated action triggered from push to main, deployed to github pages

**Describe alternatives you've considered**
Integrate vercel or similar directly with git repo, however as our site is fully static we likely don't need the added functionality so can just keep things simple for now

**Additional context**
Github actions should already have templates for nextJS actions, an example using hugo (likely similar for nextJS):
https://dev.to/github/how-to-host-a-static-nextjs-site-on-github-pages-4pe0

Alternatively can just write the action code manually.

As an additional tip, to make testing easier you may want to temporarily change the action trigger to test the action whenever you push to your dev branch. E.g. if you are working on a branch named `ft-docs-deploy`

_.github\workflows\deploy.yml_
```
name: Deploy
on:
  push:
    branches:
      - main
      - ft-docs-deploy
```

**Comment by FaithDaka** [comment]
Hi @chrismclarke 
I currently don't have permissions for this repository, so I am unable to access the _github pages_ option

**Comment by chrismclarke** [comment]
Sorry I missed your last message @FaithDaka - I tried to quickly add the default github action to deploy nextjs however it failed as its not compatible with nextra (the action creates a new config file and doesn't copy over the correct settings). But I figured things out, deployed and now available on custom domain https://docs.picsa.app so all good
